# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-domain-manager

# The `service` block is the name of the service
service: serverless-exyos

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs8.10

custom:
  customDomain:
    domainName: exyos.acari.io
    basePath: ''
    stage: prd
    createRoute53Record: true

# The `functions` block defines what code to deploy
functions:
  signBunnyAPI:
    handler: src/api/sign/index.handler
    events:
      - http:
          path: /api/sign-bunny # this matches the base path
          method: ANY
      - http:
          path: /api/sign-bunny/{any+} # this matches any path, the token 'any' doesn't mean anything special
          method: ANY
  exyos:
    handler: src/index.handler
    # The `events` block defines how to trigger the handler.helloWorld code
    events:
      - http:
          path: / # this matches the base path
          method: ANY
      - http:
          path: /{any+} # this matches any path, the token 'any' doesn't mean anything special
          method: ANY
